import type { Metadata } from "next";
import "../globals.css";
import { Roboto } from 'next/font/google'
import NavBar from "@/components/shared/NavBar/NavBar";

const roboto = Roboto({
      weight: '400',
      subsets: ['latin'],
})

export const metadata: Metadata = {
      title: "Tutor.com a online learning platform which maked by Md Abumahid Islam",
      description: "Generated by create next app",
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html lang="en">
                  <body
                        className={`${roboto.className} antialiased`}
                  >
                        <NavBar />
                        {children}
                  </body>
            </html>
      );
}
